SELECT e.NAME, e.SURNAME, d.DEPT_NAME  AS "department", d.ADDRESS AS "address"
FROM EMPLOYEES e 
LEFT JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID
ORDER BY e.SURNAME;

SELECT e.NAME, e.SURNAME, COALESCE(d.DEPT_NAME, 'no dopartment') AS "department", COALESCE(d.ADDRESS, 'no department') AS "address"
FROM EMPLOYEES e 
LEFT JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID
ORDER BY e.SURNAME; 

SELECT 
	COALESCE(e.NAME, 'no employees') AS "name",
	COALESCE(e.SURNAME, 'no employees') AS "surname", 
	COALESCE(d.DEPT_NAME, 'no dopartment') AS "department", 
	COALESCE(d.ADDRESS, 'no department') AS "address"
FROM EMPLOYEES e 
FULL OUTER JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID
ORDER BY e.SURNAME;

SELECT d.DEPT_NAME, COUNT(e.EMP_ID) AS "employees_at_dept", SUM(e.SALARY) AS "salaries_at_dept"  
FROM DEPARTMENTS d 
LEFT JOIN EMPLOYEES e ON e.DEPT_ID = d.DEPT_ID 
GROUP BY d.DEPT_NAME 
ORDER BY d.DEPT_NAME;

SELECT e.SURNAME , COALESCE(e2.SURNAME, 'no boss') AS "boss"
FROM EMPLOYEES e 
LEFT JOIN EMPLOYEES e2 ON e.BOSS_ID = e2.EMP_ID 
ORDER BY e.SURNAME;

SELECT e.SURNAME , COALESCE(e2.SURNAME, 'no boss') AS "boss"
FROM EMPLOYEES e 
LEFT JOIN EMPLOYEES e2 ON e.BOSS_ID = e2.EMP_ID 
WHERE UPPER(e2.SURNAME) IN ('WILSON', 'SMITH') OR e2.SURNAME IS NULL 
ORDER BY e.SURNAME;
-- some data is not same as in the answear
SELECT 
	e.SURNAME , 
	e.SALARY * 12 + COALESCE(e.ADD_SALARY, 0) AS "emp_annual_salary",
	e2.SALARY * 12 + COALESCE(e2.ADD_SALARY, 0) - e.SALARY * 12 - COALESCE(e.ADD_SALARY, 0) AS "less_than_boss"
FROM EMPLOYEES e 
INNER JOIN EMPLOYEES e2 ON e.BOSS_ID = e2.EMP_ID 
ORDER BY e.SURNAME; 

SELECT b.SURNAME AS "boss", COUNT(e.EMP_ID) AS "subordinates"
FROM EMPLOYEES b
LEFT JOIN EMPLOYEES e ON b.EMP_ID = e.BOSS_ID 
GROUP BY b.SURNAME 
ORDER BY b.SURNAME;

SELECT 
	e.NAME || ' ' || e.SURNAME AS "employee",
	UPPER(d.DEPT_NAME) AS "employee_department",
	e2.NAME || ' ' || e2.SURNAME AS "boss",
	UPPER(d2.DEPT_NAME) AS "employee_department"
FROM EMPLOYEES e 
INNER JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID 
INNER JOIN EMPLOYEES e2 ON e2.EMP_ID = e.BOSS_ID 
INNER JOIN DEPARTMENTS d2 ON e2.DEPT_ID = d2.DEPT_ID 
ORDER BY e.NAME , e.SURNAME;

SELECT 
	e.NAME || ' ' || e.SURNAME AS "employee",
	COALESCE(UPPER(d.DEPT_NAME), 'no department') AS "employee_department",
	CASE 
		WHEN e2.SURNAME IS NULL THEN 'no boss'
		ELSE e2.NAME || ' ' || e2.SURNAME
	END AS "boss",
	COALESCE(UPPER(d2.DEPT_NAME), 'no department') AS "employee_department"
FROM EMPLOYEES e 
LEFT OUTER JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID 
LEFT OUTER JOIN EMPLOYEES e2 ON e2.EMP_ID = e.BOSS_ID 
LEFT OUTER JOIN DEPARTMENTS d2 ON e2.DEPT_ID = d2.DEPT_ID 
ORDER BY e.NAME , e.SURNAME;

SELECT COUNT(*) AS "rows_of_cartesian_product"
FROM EMPLOYEES e CROSS JOIN DEPARTMENTS d CROSS JOIN JOBS j;

