SELECT SURNAME, EMP_ID, SUBSTR(SURNAME, 0, 2) || EMP_ID AS "login"
FROM EMPLOYEES 
ORDER BY SURNAME;
SELECT SURNAME
FROM EMPLOYEES
WHERE SURNAME  LIKE '%L%' OR SURNAME LIKE '%l%'
ORDER BY SURNAME;
SELECT SURNAME 
FROM EMPLOYEES
WHERE SUBSTR(SURNAME, 0, CEIL(LENGTH(SURNAME) / 2)) LIKE '%l%'
OR SUBSTR(SURNAME, 0, CEIL(LENGTH(SURNAME) / 2)) LIKE '%L%'
ORDER BY SURNAME;
