SELECT MIN(SALARY) AS "minimum_salary", MAX(SALARY) AS "maximum_salary", MAX(SALARY) - MIN(SALARY) AS "difference" 
FROM EMPLOYEES e;
SELECT COUNT(EMP_ID) AS "employees_without_dept"
FROM EMPLOYEES e 
WHERE DEPT_ID IS NULL;
SELECT COUNT(EMP_ID) AS "professors"
FROM EMPLOYEES e 
WHERE JOB  = 'PROFESSOR';
SELECT JOB, TO_CHAR(ROUND(AVG(SALARY), 2), '9999.99' ) AS "average salary"
FROM EMPLOYEES e
GROUP BY JOB
ORDER BY AVG(SALARY) DESC;
SELECT 
	JOB, 
	TO_CHAR(ROUND(AVG( (SALARY + COALESCE(ADD_SALARY, 0) )), 2), '9999.99' ) AS "average salary",
	COUNT(*) AS "employees"
FROM EMPLOYEES e
GROUP BY JOB
ORDER BY AVG(SALARY) DESC;
SELECT 
	JOB, 
	TO_CHAR(ROUND(AVG( (SALARY + COALESCE(ADD_SALARY, 0) )), 2), '9999.99' ) AS "average salary",
	COUNT(*) AS "employees"
FROM EMPLOYEES e
GROUP BY JOB
HAVING COUNT(*) > 1
ORDER BY AVG(SALARY) DESC;
SELECT DEPT_ID, COUNT(*) AS "employees with add salary" 
FROM EMPLOYEES e 
WHERE DEPT_ID IS NOT NULL AND ADD_SALARY IS NULL 
GROUP BY DEPT_ID
ORDER BY DEPT_ID;
