SELECT MIN(SALARY) AS "minimum_salary", MAX(SALARY) AS "maximum_salary", MAX(SALARY) - MIN(SALARY) AS "difference" 
FROM EMPLOYEES e;
SELECT COUNT(EMP_ID) AS "employees_without_dept"
FROM EMPLOYEES e 
WHERE DEPT_ID IS NULL;
SELECT COUNT(EMP_ID) AS "professors"
FROM EMPLOYEES e 
WHERE JOB  = 'PROFESSOR';
SELECT JOB, TO_CHAR(ROUND(AVG(SALARY), 2), '9999.99' ) AS "average salary"
FROM EMPLOYEES e
GROUP BY JOB
ORDER BY AVG(SALARY) DESC;
SELECT 
	JOB, 
	TO_CHAR(ROUND(AVG( (SALARY + COALESCE(ADD_SALARY, 0) )), 2), '9999.99' ) AS "average salary",
	COUNT(*) AS "employees"
FROM EMPLOYEES e
GROUP BY JOB
ORDER BY AVG(SALARY) DESC;
SELECT 
	JOB, 
	TO_CHAR(ROUND(AVG( (SALARY + COALESCE(ADD_SALARY, 0) )), 2), '9999.99' ) AS "average salary",
	COUNT(*) AS "employees"
FROM EMPLOYEES e
GROUP BY JOB
HAVING COUNT(*) > 1
ORDER BY AVG(SALARY) DESC;
SELECT DEPT_ID, COUNT(*) AS "employees with add salary" 
FROM EMPLOYEES e 
WHERE DEPT_ID IS NOT NULL AND ADD_SALARY IS NOT NULL 
GROUP BY DEPT_ID
ORDER BY DEPT_ID;
SELECT 
	DEPT_ID, 
	COUNT(*) AS "employees with add salary",
	AVG(ADD_SALARY) AS "average add salary",
	SUM(ADD_SALARY) AS "sum of add salaries" 
FROM EMPLOYEES e 
WHERE DEPT_ID IS NOT NULL AND ADD_SALARY IS NOT NULL 
GROUP BY DEPT_ID
ORDER BY DEPT_ID;
SELECT BOSS_ID, COUNT(*) AS "number of subordinates" 
FROM EMPLOYEES e 
WHERE BOSS_ID IS NOT NULL 
GROUP BY BOSS_ID 
ORDER BY BOSS_ID;
SELECT 
	EXTRACT(YEAR FROM hire_date) AS "year_of_employment",
	COUNT(*) AS "number_of_employees"
FROM EMPLOYEES e 
GROUP BY EXTRACT(YEAR FROM hire_date)
ORDER BY EXTRACT(YEAR FROM hire_date);
SELECT LENGTH(SURNAME) AS "surname_lenght", COUNT(*) AS "number_of_surnames" 
FROM EMPLOYEES e 
GROUP BY LENGTH(SURNAME)
ORDER BY LENGTH(SURNAME);
SELECT  COUNT(*) AS "surnames_with_a"
FROM EMPLOYEES e 
WHERE LOWER(SURNAME) LIKE '%a%';
SELECT  COUNT(*) AS "surnames_with_e"
FROM EMPLOYEES e 
WHERE LOWER(SURNAME) LIKE '%e%';
SELECT 
	SUM(CASE 
		WHEN (lower(SURNAME) LIKE '%a%') THEN 1
		ELSE 0
	END) AS "surnames_with_a",
	SUM(CASE
		WHEN (lower(SURNAME) LIKE '%e%') THEN 1
		ELSE 0
	END) AS "surnames_with_e" 
FROM EMPLOYEES e;