--task1
SELECT e.SURNAME, e.JOB
FROM EMPLOYEES e 
WHERE e.DEPT_ID = 
		(SELECT DEPT_ID
		FROM EMPLOYEES e2 WHERE SURNAME = 'Johnson')
	AND SURNAME != 'Johnson'
ORDER BY e.SURNAME;
--task2
SELECT e.SURNAME, e.JOB, d.DEPT_NAME 
FROM EMPLOYEES e INNER JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID 
WHERE e.DEPT_ID = 
		(SELECT DEPT_ID
		FROM EMPLOYEES e2 WHERE SURNAME = 'Johnson')
	AND SURNAME != 'Johnson'
ORDER BY e.SURNAME;
--task3
SELECT e.SURNAME , e.JOB, e.HIRE_DATE 
FROM EMPLOYEES e 
WHERE e.HIRE_DATE = 
	(SELECT MIN(e2.HIRE_DATE) 
	FROM EMPLOYEES e2 WHERE e2.JOB = 'LECTURER')
	AND JOB = 'LECTURER';
--task4
SELECT d.DEPT_NAME AS "department", e.SURNAME, e.HIRE_DATE 
FROM DEPARTMENTS d INNER JOIN EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID 
WHERE (d.DEPT_ID, e.HIRE_DATE) = ANY
	(SELECT e2.DEPT_ID, MAX(e2.HIRE_DATE) 
	FROM EMPLOYEES e2 GROUP BY e2.DEPT_ID)
ORDER BY d.DEPT_NAME ;
--task5
SELECT *
FROM DEPARTMENTS d 
WHERE d.DEPT_ID NOT IN (SELECT DISTINCT e.DEPT_ID FROM EMPLOYEES e WHERE e.DEPT_ID IS NOT NULL);
--task6
SELECT e.SURNAME, e.JOB, e.SALARY 
FROM EMPLOYEES e 
WHERE e.EMP_ID NOT IN (SELECT DISTINCT e2.BOSS_ID  FROM EMPLOYEES e2 WHERE LOWER(e2.JOB) = 'phd student')
	AND LOWER(e.JOB) = 'professor' 
ORDER BY e.SURNAME;
--task7
SELECT d.DEPT_NAME AS "department", n.num AS "num_of_empl"
FROM DEPARTMENTS d INNER JOIN 
	(SELECT e.DEPT_ID, COUNT(*) AS num 
	FROM EMPLOYEES e GROUP BY e.DEPT_ID
	HAVING COUNT(*) > 
		(SELECT COUNT(*) FROM EMPLOYEES e2
		WHERE e2.DEPT_ID = 
			(SELECT d2.DEPT_ID FROM DEPARTMENTS d2 
			WHERE LOWER(d2.DEPT_NAME) = 'administration')
		)
	) n ON n.DEPT_ID = d.DEPT_ID
ORDER BY d.DEPT_NAME;
--task8
SELECT YEAR_OF_EMPLOYMENT, NUMBER_OF_PROFESSORS
FROM (SELECT EXTRACT( YEAR FROM e.HIRE_DATE) AS year_of_employment, COUNT(*) AS number_of_professors
	FROM EMPLOYEES e 
	WHERE LOWER(e.JOB) = 'professor'
	GROUP BY EXTRACT( YEAR FROM e.HIRE_DATE)
	ORDER BY EXTRACT( YEAR FROM e.HIRE_DATE))
WHERE NUMBER_OF_PROFESSORS >= ALL 
	(SELECT COUNT(*)
	FROM EMPLOYEES e 
	WHERE LOWER(e.JOB) = 'professor'
	GROUP BY EXTRACT( YEAR FROM e.HIRE_DATE))
ORDER BY YEAR_OF_EMPLOYMENT;
--task9
SELECT d.DEPT_NAME, s.spendings
FROM DEPARTMENTS d INNER JOIN 
	(SELECT SUM(e.salary + COALESCE(e.add_salary, 0)) AS spendings, e.DEPT_ID
	FROM EMPLOYEES e
	GROUP BY e.DEPT_ID) s ON d.DEPT_ID = s.DEPT_ID
WHERE s.spendings >= ALL
	(SELECT SUM(e.salary + COALESCE(e.add_salary, 0))
	FROM EMPLOYEES e
	GROUP BY e.DEPT_ID)
;


