SELECT e.SURNAME, e.JOB
FROM EMPLOYEES e 
WHERE e.DEPT_ID = 
		(SELECT DEPT_ID
		FROM EMPLOYEES e2 WHERE SURNAME = 'Johnson')
	AND SURNAME != 'Johnson'
ORDER BY e.SURNAME;

SELECT e.SURNAME, e.JOB, d.DEPT_NAME 
FROM EMPLOYEES e INNER JOIN DEPARTMENTS d ON d.DEPT_ID = e.DEPT_ID 
WHERE e.DEPT_ID = 
		(SELECT DEPT_ID
		FROM EMPLOYEES e2 WHERE SURNAME = 'Johnson')
	AND SURNAME != 'Johnson'
ORDER BY e.SURNAME;

SELECT e.SURNAME , e.JOB, e.HIRE_DATE 
FROM EMPLOYEES e 
WHERE e.HIRE_DATE = 
	(SELECT MIN(e2.HIRE_DATE) 
	FROM EMPLOYEES e2 WHERE e2.JOB = 'LECTURER')
	AND JOB = 'LECTURER';

SELECT d.DEPT_NAME AS "department", e.SURNAME, e.HIRE_DATE 
FROM DEPARTMENTS d INNER JOIN EMPLOYEES e ON d.DEPT_ID = e.DEPT_ID 
WHERE (d.DEPT_ID, e.HIRE_DATE) = ANY
	(SELECT e2.DEPT_ID, MAX(e2.HIRE_DATE) 
	FROM EMPLOYEES e2 GROUP BY e2.DEPT_ID)
ORDER BY d.DEPT_NAME ;
--doesn't work as expected
SELECT *
FROM DEPARTMENTS d 
WHERE d.DEPT_ID NOT IN (SELECT e.DEPT_ID FROM EMPLOYEES e);

SELECT e.SURNAME, e.JOB, e.SALARY 
FROM EMPLOYEES e 
WHERE e.EMP_ID NOT IN (SELECT UNIQUE e2.BOSS_ID  FROM EMPLOYEES e2 WHERE LOWER(e2.JOB) = 'phd student')
	AND LOWER(e.JOB) = 'professor' 
ORDER BY e.SURNAME;

SELECT d.DEPT_NAME AS "department", n.num AS "num_of_empl"
FROM DEPARTMENTS d INNER JOIN (SELECT e.DEPT_ID, COUNT(*) AS num 
								FROM EMPLOYEES e GROUP BY e.DEPT_ID
								HAVING COUNT(*) > 
									(SELECT COUNT(*) FROM EMPLOYEES e2
									WHERE e2.DEPT_ID =
										(SELECT d2.DEPT_ID FROM DEPARTMENTS d2 
										WHERE LOWER(d2.DEPT_NAME) = 'administration')
									)
								) n 
						ON n.DEPT_ID = d.DEPT_ID
ORDER BY d.DEPT_NAME;
--need some fixes
SELECT EXTRACT( YEAR FROM e.HIRE_DATE) AS "year", COUNT(*) AS "number_of_professors"
FROM EMPLOYEES e 
WHERE LOWER(e.JOB) = 'professor'
GROUP BY EXTRACT( YEAR FROM e.HIRE_DATE)
ORDER BY EXTRACT( YEAR FROM e.HIRE_DATE);
